[phases.setup]
nixpkgs = ["gcc", "libpq", "postgresql_16", "python38"]

[phases.build]
cmds = [
    "pip install --no-cache-dir -r requirements.txt",  # Install Python dependencies
]

[start]
cmd = "FLASK_APP=server.app PYTHONPATH=server gunicorn -b 0.0.0.0:8000 app:app"  # Start Flask app with Gunicorn